[package]
name = "examples-subscriptions"
version = "0.0.0"
publish = false
authors = ["Andrea Simeoni <andreasimeoni84@gmail.com>"]

license.workspace = true
rust-version.workspace = true
edition.workspace = true

[dev-dependencies]
ethers = { workspace = true, features = ["abigen", "ws", "rustls"] }

tokio = { workspace = true, features = ["macros"] }

serde.workspace = true
serde_json.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tracing.workspace = true
eyre.workspace = true

[[example]]
name = "subscribe-events-by-type"
path = "examples/subscribe_events_by_type.rs"

[[example]]
name = "subscribe-blocks"
path = "examples/subscribe_blocks.rs"

[[example]]
name = "subscribe-logs"
path = "examples/subscribe_logs.rs"